title: Relax and stretch
hero_image: images/relax-banner.png
description: Write a program to help you and others stay healthy while you are seated
version: 5
listed: false
copyedit: false
last_tested: "2020-05-26"
steps:
  - title: Introduction
  - title: Prepare your character
  - title: Breathe
  - title: Control the repetitions
  - title: Add control to the buttons
  - title: Add a head roll exercise
  - title: "Challenge: add your own exercise routine"
    challenge: true
  - title: Share your project
  - title: What next?
