title: Sit and stretch
hero_image: images/banner.png
description: sit-stretch description
version: 4
listed: false
copyedit: false
last_tested: "2020-05-26"
steps:
  - title: Introduction
  - title: Getting your character ready
  - title: Getting the arrows ready 
  - title: Exercise 1
  - title: The repetitions variable
  - title: Arrow button controls
  - title: Exercise 2
  - title: "Challenge: Add your own exercise routine"
    challenge: true
  - title: What next?
