title: Sit and stretch
hero_image: images/banner.png
description: sit-stretch description
version: 5
listed: false
copyedit: false
last_tested: "2020-05-26"
steps:
  - title: Introduction
  - title: Get your character ready
  - title: Get the arrows ready 
  - title: Breathe
  - title: Repetitions
  - title: Add control to the buttons
  - title: Head roll
  - title: "Challenge: Add your own exercise routine"
    challenge: true
  - title: Share your project
  - title: What next?
