---
title: Relax and stretch
hero_image: images/relax-banner.png
description: Write a program to help you and others stay healthy while you are seated
version: 5
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
- title: Introduction
  completion: engaged
- title: Prepare your character
- title: Add a breathing exercise
- title: Control the repetitions
- title: Code the buttons
- title: Add a head roll exercise
  completion: internal
- title: Add more
- title: Share
- title: What next?
